fn main() {
    println!();
    println!("Available commands:");
    println!();
    println!("  help              - Display this help message");
    println!("  clear             - Clear the screen");
    println!("  ls [path] [-l]    - List directory contents");
    println!("  cd [dir]          - Change directory (no arg = root)");
    println!("  pwd               - Print working directory");
    println!("  mkdir [-p] <dir>  - Create directory");
    println!("  cat <file> ...    - Display file contents");
    println!("  edit <file>       - Edit a file");
    println!("  touch <file>      - Create empty file");
    println!("  cp <src> <dst>    - Copy file");
    println!("  mv <src> <dst>    - Move/rename file");
    println!("  rm [-r] <file>... - Delete files or directories");
    println!("  echo [-n|-e] text - Print text");
    println!("  python [file]     - Start Python REPL or run script");
    println!("  git <command>     - Version control (init/add/commit/log/...)");
    println!("  peripherals [name]- List peripherals or methods");
    println!("  visual            - Open visual programming editor");
    println!();
    println!("Networking:");
    println!("  ifconfig <iface>   - Show/set interface configuration");
    println!("  ip addr            - Show/manage interface addresses");
    println!("  switch             - L2 switch CLI (MAC table, VLANs)");
    println!("  ip route           - Show/manage routing table");
    println!("  ip link            - Show/manage link-layer info");
    println!("  ping <ip> [count]  - Send ICMP echo requests");
    println!("  nslookup <host>    - DNS lookup");
    println!("  resolvectl status  - Show DNS configuration");
    println!("  resolvectl dns ..  - Set DNS server");
    println!("  httpd <port>       - Start HTTP server (blocks shell)");
    println!("  sshd [port]        - Start SSH server (default: 22)");
    println!("  curl <url>         - HTTP client (GET/POST)");
    println!("  ssh [user@]host    - SSH client (connect to remote)");
    println!();
    println!("Process management:");
    println!("  ps                - List running processes");
    println!("  kill <pid>        - Kill a process by PID");
    println!("  jobs              - List background jobs");
    println!("  fg %<id>|<pid>    - Bring job to foreground (wait for exit)");
    println!("  bg                - Continue job in background");
    println!("  <program>         - Run a .wasm program (searches bin/)");
    println!("  <program> &       - Run program in background");
    println!();
    println!("System shortcuts:");
    println!("  Ctrl+T      - Terminate current program (kill)");
    println!();
    println!("Editor shortcuts:");
    println!("  Ctrl+S  Save   Ctrl+E  Exit   Ctrl+R  Save & run");
    println!("  Ctrl+F  Find   Ctrl+X  Cut    Ctrl+C  Copy");
    println!("  Ctrl+V  Paste  Ctrl+D  Delete Ctrl+K  Clear line");
}
