//! `running_config`: serialize the configuration as replayable CLI text
//! (`/switch.cfg`). Blocks are closed with an indented-context `exit`, which
//! only pops back to the top level; the output never contains a top-level
//! `exit`.

use super::format_vlan_list;
use crate::bridge::{fmt_ip, fmt_mac, Bridge};
use crate::frame::HashMode;
use crate::log::DEFAULT_SEVERITY;
use crate::types::*;
use ecm_net::types::Ipv4Addr;
use std::collections::BTreeMap;
use std::fmt::Write;

fn mode_lines(out: &mut String, m: &PortMode) {
    match m {
        PortMode::Routed => {}
        PortMode::Access { vid } => {
            out.push_str(" no routing\n");
            if *vid != DEFAULT_VID {
                let _ = writeln!(out, " vlan access {}", vid);
            }
        }
        PortMode::Trunk { native, native_tag, allowed } => {
            out.push_str(" no routing\n");
            let _ = writeln!(out, " vlan trunk native {}{}", native, if *native_tag { " tag" } else { "" });
            match allowed {
                AllowedList::All => {}
                AllowedList::Some(s) if s.is_empty() => {
                    // Reproduce an emptied list.
                    out.push_str(" vlan trunk allowed 1\n no vlan trunk allowed 1\n");
                }
                AllowedList::Some(s) => {
                    let _ = writeln!(out, " vlan trunk allowed {}", format_vlan_list(s));
                }
            }
        }
    }
}

fn stp_lines(out: &mut String, c: &StpPortConfig) {
    let d = StpPortConfig::default();
    if !c.enabled {
        out.push_str(" no spanning-tree\n");
    }
    if c.priority != d.priority {
        let _ = writeln!(out, " spanning-tree port-priority {}", c.priority);
    }
    if c.cost != d.cost {
        let _ = writeln!(out, " spanning-tree cost {}", c.cost);
    }
    if c.admin_edge {
        out.push_str(" spanning-tree admin-edge-port\n");
    }
    if c.bpdu_guard {
        out.push_str(" spanning-tree bpdu-guard\n");
    }
    if c.root_guard {
        out.push_str(" spanning-tree root-guard\n");
    }
    if c.tcn_guard {
        out.push_str(" spanning-tree tcn-guard\n");
    }
}

/// Serialize the running configuration. SVI addresses are taken from the
/// bridge; entries in `svis` override/add to them (pass `&[]` to use only
/// the bridge's own record).
pub fn running_config(b: &Bridge, svis: &[(u16, Ipv4Addr, u8)]) -> String {
    let c = b.config_snapshot();
    let mut out = String::new();
    out.push_str("# switch.cfg - generated by 'write memory'\n");

    if c.age_time_secs != DEFAULT_AGE_TIME_SECS {
        let _ = writeln!(out, "mac-address-table age-time {}", c.age_time_secs);
    }

    // Logging
    if c.log.severity != DEFAULT_SEVERITY {
        let _ = writeln!(out, "logging severity {}", c.log.severity.as_str());
    }
    if c.log.console {
        out.push_str("logging console\n");
    }
    for r in &c.log.remotes {
        let _ = writeln!(out, "logging {}", fmt_ip(&Ipv4Addr(*r)));
    }

    // LLDP globals
    let l = &c.lldp;
    if !l.enabled {
        out.push_str("no lldp\n");
    }
    if l.timer_secs != DEFAULT_LLDP_TIMER {
        let _ = writeln!(out, "lldp timer {}", l.timer_secs);
    }
    if l.holdtime != DEFAULT_LLDP_HOLDTIME {
        let _ = writeln!(out, "lldp holdtime {}", l.holdtime);
    }
    if l.reinit_secs != DEFAULT_LLDP_REINIT {
        let _ = writeln!(out, "lldp reinit {}", l.reinit_secs);
    }
    if l.txdelay_secs != DEFAULT_LLDP_TXDELAY {
        let _ = writeln!(out, "lldp txdelay {}", l.txdelay_secs);
    }
    if let Some(ip) = l.mgmt_ipv4 {
        let _ = writeln!(out, "lldp management-ipv4-address {}", fmt_ip(&Ipv4Addr(ip)));
    }
    for t in LldpTlv::ALL {
        if !l.tlv(t) {
            let _ = writeln!(out, "no lldp select-tlv {}", t.name());
        }
    }

    // Spanning tree globals
    let s = &c.stp;
    if s.enabled {
        out.push_str("spanning-tree\n");
    }
    if s.priority != DEFAULT_BRIDGE_PRIORITY {
        let _ = writeln!(out, "spanning-tree priority {}", s.priority);
    }
    if s.forward_delay_secs != DEFAULT_FORWARD_DELAY_SECS {
        let _ = writeln!(out, "spanning-tree forward-delay {}", s.forward_delay_secs);
    }
    if s.hello_secs != DEFAULT_HELLO_SECS {
        let _ = writeln!(out, "spanning-tree hello-time {}", s.hello_secs);
    }
    if s.max_age_secs != DEFAULT_MAX_AGE_SECS {
        let _ = writeln!(out, "spanning-tree max-age {}", s.max_age_secs);
    }
    if !s.config_name.is_empty() {
        let _ = writeln!(out, "spanning-tree config-name {}", s.config_name);
    }
    if s.config_revision != 0 {
        let _ = writeln!(out, "spanning-tree config-revision {}", s.config_revision);
    }

    // VLANs
    for v in &c.vlans {
        let default_vlan = v.vid == DEFAULT_VID;
        if default_vlan && v.name.as_deref() == Some("default") && v.description.is_none() {
            continue;
        }
        let _ = writeln!(out, "vlan {}", v.vid);
        match &v.name {
            Some(n) if !(default_vlan && n == "default") => {
                let _ = writeln!(out, " name {}", n);
            }
            None if default_vlan => out.push_str(" no name\n"),
            _ => {}
        }
        if let Some(d) = &v.description {
            let _ = writeln!(out, " description {}", d);
        }
        if !default_vlan {
            out.push_str(if v.active { " no shutdown\n" } else { " shutdown\n" });
        }
        out.push_str(" exit\n");
    }

    // LAGs
    for g in &c.lags {
        let _ = writeln!(out, "interface lag {}", g.id);
        mode_lines(&mut out, &g.mode);
        if !g.admin_up {
            out.push_str(" shutdown\n");
        }
        match g.lacp_mode {
            LacpMode::Off => {}
            LacpMode::Active => out.push_str(" lacp mode active\n"),
            LacpMode::Passive => out.push_str(" lacp mode passive\n"),
        }
        if g.lacp_rate == LacpRate::Fast {
            out.push_str(" lacp rate fast\n");
        }
        if g.fallback {
            out.push_str(" lacp fallback\n");
        }
        match g.hash {
            HashMode::L3 => {}
            h => {
                let _ = writeln!(out, " hash {}", h.as_str());
            }
        }
        stp_lines(&mut out, &g.stp);
        out.push_str(" exit\n");
    }

    // Physical ports
    let def = EthConfig::default();
    for (i, e) in c.eth.iter().enumerate() {
        if *e == def {
            continue;
        }
        let _ = writeln!(out, "interface eth{}", i);
        mode_lines(&mut out, &e.mode);
        if !e.admin_up {
            out.push_str(" shutdown\n");
        }
        if let Some(id) = e.lag {
            let _ = writeln!(out, " lag {}", id);
        }
        if !e.lldp_tx {
            out.push_str(" no lldp transmit\n");
        }
        if !e.lldp_rx {
            out.push_str(" no lldp receive\n");
        }
        stp_lines(&mut out, &e.stp);
        out.push_str(" exit\n");
    }

    // SVIs
    let mut svi_map: BTreeMap<u16, (Ipv4Addr, u8)> = c.svis.iter().map(|(v, ip, p)| (*v, (Ipv4Addr(*ip), *p))).collect();
    for (v, ip, p) in svis {
        svi_map.insert(*v, (*ip, *p));
    }
    for (v, (ip, p)) in &svi_map {
        let _ = writeln!(out, "interface vlan {}", v);
        let _ = writeln!(out, " ip address {}/{}", fmt_ip(ip), p);
        out.push_str(" exit\n");
    }

    // Static MACs
    for st in &c.statics {
        let port = match st.port {
            PortRef::Eth(n) => n.to_string(),
            other => other.to_string(),
        };
        let _ = writeln!(out, "static-mac {} vlan {} port {}", fmt_mac(&st.mac), st.vlan, port);
    }
    out
}
