"""Auto-generated CC:Tweaked peripheral wrappers.

This file contains wrapper classes for all discovered CC:Tweaked peripherals.
Generated by PythonStubGenerator - do not edit manually.
"""

import peripheral

def _parse_json_result(json_str):
    if json_str is None: return None
    json_str = json_str.strip()
    if json_str == 'null': return None
    if json_str == 'true': return True
    if json_str == 'false': return False
    if json_str.startswith('"') and json_str.endswith('"'): return json_str[1:-1]
    try:
        return float(json_str) if '.' in json_str else int(json_str)
    except: return json_str

def _parse_string_array(json_str):
    if not json_str or not json_str.strip().startswith('['): return []
    inner = json_str.strip()[1:-1].strip()
    if not inner: return []
    return [i.strip().strip('"') for i in inner.split(',') if i.strip()]

class PlayerDetector:
    """Wrapper for player_detector peripheral."""

    def __init__(self, name):
        self.name = name
        if not peripheral.is_present(name):
            raise ValueError(f'Peripheral not found: {name}')

    @staticmethod
    def find():
        name = peripheral.find('player_detector')
        return PlayerDetector(name) if name else None

    def get_players_in_cubic(self, arg0, arg1, arg2):
        """Call the getPlayersInCubic method.

        Args:
            arg0: int
            arg1: int
            arg2: int

        Returns:
            any
        """
        args = '['
        args += str(arg0)
        args += ','
        args += str(arg1)
        args += ','
        args += str(arg2)
        args += ']'
        result = peripheral.call(self.name, 'getPlayersInCubic', args)
        return _parse_string_array(result)

    def get_players_in_range(self, arg0):
        """Call the getPlayersInRange method.

        Args:
            arg0: int

        Returns:
            any
        """
        args = '['
        args += str(arg0)
        args += ']'
        result = peripheral.call(self.name, 'getPlayersInRange', args)
        return _parse_string_array(result)

    def is_players_in_coords(self, arg0, arg1):
        """Call the isPlayersInCoords method.

        Args:
            arg0: Map
            arg1: Map

        Returns:
            bool
        """
        args = '['
        args += str(arg0)
        args += ','
        args += str(arg1)
        args += ']'
        result = peripheral.call(self.name, 'isPlayersInCoords', args)
        return _parse_json_result(result)

    def is_player_in_cubic(self, arg0, arg1, arg2, arg3):
        """Call the isPlayerInCubic method.

        Args:
            arg0: int
            arg1: int
            arg2: int
            arg3: String

        Returns:
            bool
        """
        args = '['
        args += str(arg0)
        args += ','
        args += str(arg1)
        args += ','
        args += str(arg2)
        args += ','
        args += f'"{arg3}"'
        args += ']'
        result = peripheral.call(self.name, 'isPlayerInCubic', args)
        return _parse_json_result(result)

    def get_player_pos(self):
        """Call the getPlayerPos method.

        Returns:
            dict
        """
        args = '[]'
        result = peripheral.call(self.name, 'getPlayerPos', args)
        return _parse_json_result(result)

    def get_player(self):
        """Call the getPlayer method.

        Returns:
            dict
        """
        args = '[]'
        result = peripheral.call(self.name, 'getPlayer', args)
        return _parse_json_result(result)

    def is_player_in_coords(self, arg0, arg1, arg2):
        """Call the isPlayerInCoords method.

        Args:
            arg0: Map
            arg1: Map
            arg2: String

        Returns:
            bool
        """
        args = '['
        args += str(arg0)
        args += ','
        args += str(arg1)
        args += ','
        args += f'"{arg2}"'
        args += ']'
        result = peripheral.call(self.name, 'isPlayerInCoords', args)
        return _parse_json_result(result)

    def is_player_in_range(self, arg0, arg1):
        """Call the isPlayerInRange method.

        Args:
            arg0: int
            arg1: String

        Returns:
            bool
        """
        args = '['
        args += str(arg0)
        args += ','
        args += f'"{arg1}"'
        args += ']'
        result = peripheral.call(self.name, 'isPlayerInRange', args)
        return _parse_json_result(result)

    def is_players_in_range(self, arg0):
        """Call the isPlayersInRange method.

        Args:
            arg0: int

        Returns:
            bool
        """
        args = '['
        args += str(arg0)
        args += ']'
        result = peripheral.call(self.name, 'isPlayersInRange', args)
        return _parse_json_result(result)

    def is_players_in_cubic(self, arg0, arg1, arg2):
        """Call the isPlayersInCubic method.

        Args:
            arg0: int
            arg1: int
            arg2: int

        Returns:
            bool
        """
        args = '['
        args += str(arg0)
        args += ','
        args += str(arg1)
        args += ','
        args += str(arg2)
        args += ']'
        result = peripheral.call(self.name, 'isPlayersInCubic', args)
        return _parse_json_result(result)

    def get_players_in_coords(self, arg0, arg1):
        """Call the getPlayersInCoords method.

        Args:
            arg0: Map
            arg1: Map

        Returns:
            any
        """
        args = '['
        args += str(arg0)
        args += ','
        args += str(arg1)
        args += ']'
        result = peripheral.call(self.name, 'getPlayersInCoords', args)
        return _parse_json_result(result)

    def get_online_players(self):
        """Call the getOnlinePlayers method.

        Returns:
            list
        """
        args = '[]'
        result = peripheral.call(self.name, 'getOnlinePlayers', args)
        return _parse_string_array(result)

    def get_configuration(self):
        """Call the getConfiguration method.

        Returns:
            dict
        """
        args = '[]'
        result = peripheral.call(self.name, 'getConfiguration', args)
        return _parse_json_result(result)

    def get_name(self):
        """Call the getName method.

        Returns:
            str
        """
        args = '[]'
        result = peripheral.call(self.name, 'getName', args)
        return _parse_json_result(result)


