package com.example.customworld.stubgen;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates Python stub files from peripheral definitions.
 * Each peripheral type gets its own .py file with a wrapper class.
 */
public class PythonStubGenerator {
    
    /**
     * Generates Python stubs for all peripherals in the definitions.
     * 
     * @param definitions The peripheral definitions to generate from
     * @param outputDir The directory to write .py files to
     */
    public void generate(PeripheralDefinitions definitions, Path outputDir) throws IOException {
        Files.createDirectories(outputDir);
        
        // Generate __init__.py to make it a package
        generateInitFile(definitions, outputDir);
        
        // Generate a file for each peripheral
        for (PeripheralDefinition peripheral : definitions.getPeripherals()) {
            generatePeripheralFile(peripheral, outputDir);
        }
    }
    
    /**
     * Generates the __init__.py file that imports all peripherals.
     */
    private void generateInitFile(PeripheralDefinitions definitions, Path outputDir) throws IOException {
        StringBuilder sb = new StringBuilder();
        sb.append("\"\"\"Auto-generated CC:Tweaked peripheral wrappers.\n\n");
        sb.append("Usage:\n");
        sb.append("    from player_detector import PlayerDetector\n");
        sb.append("    detector = PlayerDetector.find()\n");
        sb.append("    if detector:\n");
        sb.append("        players = detector.get_online_players()\n");
        sb.append("\"\"\"\n\n");
        
        // Import all peripheral classes
        for (PeripheralDefinition peripheral : definitions.getPeripherals()) {
            String moduleName = peripheral.toPythonModuleName();
            String className = peripheral.toPythonClassName();
            sb.append("from ").append(moduleName).append(" import ").append(className).append("\n");
        }
        
        sb.append("\n__all__ = [\n");
        for (PeripheralDefinition peripheral : definitions.getPeripherals()) {
            sb.append("    '").append(peripheral.toPythonClassName()).append("',\n");
        }
        sb.append("]\n");
        
        Files.writeString(outputDir.resolve("__init__.py"), sb.toString(), StandardCharsets.UTF_8);
    }
    
    /**
     * Generates a Python file for a single peripheral.
     */
    private void generatePeripheralFile(PeripheralDefinition peripheral, Path outputDir) throws IOException {
        String moduleName = peripheral.toPythonModuleName();
        String className = peripheral.toPythonClassName();
        String peripheralType = peripheral.getType();
        
        StringBuilder sb = new StringBuilder();
        
        // File header
        sb.append("\"\"\"Auto-generated wrapper for ").append(peripheralType).append(" peripheral.\n\n");
        sb.append("This file was generated by PythonStubGenerator.\n");
        sb.append("Do not edit manually - changes will be overwritten.\n");
        sb.append("\"\"\"\n\n");
        sb.append("import peripheral\n\n");
        
        // Helper function for parsing results
        sb.append("def _parse_json_result(json_str):\n");
        sb.append("    \"\"\"Parse a JSON result, handling common types.\"\"\"\n");
        sb.append("    if json_str is None:\n");
        sb.append("        return None\n");
        sb.append("    json_str = json_str.strip()\n");
        sb.append("    if json_str == 'null':\n");
        sb.append("        return None\n");
        sb.append("    if json_str == 'true':\n");
        sb.append("        return True\n");
        sb.append("    if json_str == 'false':\n");
        sb.append("        return False\n");
        sb.append("    if json_str.startswith('\"') and json_str.endswith('\"'):\n");
        sb.append("        return json_str[1:-1]\n");
        sb.append("    try:\n");
        sb.append("        if '.' in json_str:\n");
        sb.append("            return float(json_str)\n");
        sb.append("        return int(json_str)\n");
        sb.append("    except:\n");
        sb.append("        pass\n");
        sb.append("    # For arrays/objects, return raw string (user can parse)\n");
        sb.append("    return json_str\n\n");
        
        sb.append("def _parse_string_array(json_str):\n");
        sb.append("    \"\"\"Parse a JSON array of strings.\"\"\"\n");
        sb.append("    if not json_str or not json_str.strip().startswith('['):\n");
        sb.append("        return []\n");
        sb.append("    json_str = json_str.strip()[1:-1].strip()\n");
        sb.append("    if not json_str:\n");
        sb.append("        return []\n");
        sb.append("    result = []\n");
        sb.append("    for item in json_str.split(','):\n");
        sb.append("        item = item.strip()\n");
        sb.append("        if item.startswith('\"') and item.endswith('\"'):\n");
        sb.append("            result.append(item[1:-1])\n");
        sb.append("        elif item:\n");
        sb.append("            result.append(item)\n");
        sb.append("    return result\n\n");
        
        // Class definition
        sb.append("class ").append(className).append(":\n");
        sb.append("    \"\"\"Wrapper for CC:Tweaked ").append(peripheralType).append(" peripheral.\n\n");
        sb.append("    This class provides typed methods for interacting with the peripheral.\n");
        sb.append("    \"\"\"\n\n");
        
        // Constructor
        sb.append("    def __init__(self, name):\n");
        sb.append("        \"\"\"Wrap an existing peripheral by name.\n\n");
        sb.append("        Args:\n");
        sb.append("            name: The peripheral name (e.g., '").append(peripheralType).append("_0')\n\n");
        sb.append("        Raises:\n");
        sb.append("            ValueError: If the peripheral doesn't exist\n");
        sb.append("        \"\"\"\n");
        sb.append("        self.name = name\n");
        sb.append("        if not peripheral.is_present(name):\n");
        sb.append("            raise ValueError(f'Peripheral not found: {name}')\n\n");
        
        // Static find method
        sb.append("    @staticmethod\n");
        sb.append("    def find():\n");
        sb.append("        \"\"\"Find the first ").append(peripheralType).append(" peripheral.\n\n");
        sb.append("        Returns:\n");
        sb.append("            ").append(className).append(" instance, or None if not found\n");
        sb.append("        \"\"\"\n");
        sb.append("        name = peripheral.find('").append(peripheralType).append("')\n");
        sb.append("        if name:\n");
        sb.append("            return ").append(className).append("(name)\n");
        sb.append("        return None\n\n");
        
        // Generate methods
        for (MethodDefinition method : peripheral.getMethods()) {
            generateMethod(sb, method);
        }
        
        Files.writeString(outputDir.resolve(moduleName + ".py"), sb.toString(), StandardCharsets.UTF_8);
    }
    
    /**
     * Generates a Python method for a peripheral method.
     */
    private void generateMethod(StringBuilder sb, MethodDefinition method) {
        String pythonName = method.toPythonName();
        String luaName = method.getLuaName();
        List<ParameterDefinition> params = method.getParameters();
        
        // Method signature
        sb.append("    def ").append(pythonName).append("(self");
        for (ParameterDefinition param : params) {
            sb.append(", ").append(param.toSnakeCaseName());
            if (param.isOptional()) {
                sb.append("=None");
            }
        }
        sb.append("):\n");
        
        // Docstring
        sb.append("        \"\"\"");
        if (method.getDescription() != null && !method.getDescription().isEmpty()) {
            sb.append(method.getDescription());
        } else {
            sb.append("Call the ").append(luaName).append(" method.");
        }
        sb.append("\n\n");
        
        if (!params.isEmpty()) {
            sb.append("        Args:\n");
            for (ParameterDefinition param : params) {
                sb.append("            ").append(param.toSnakeCaseName());
                sb.append(": ").append(param.getType());
                if (param.isOptional()) {
                    sb.append(" (optional)");
                }
                sb.append("\n");
            }
            sb.append("\n");
        }
        
        sb.append("        Returns:\n");
        sb.append("            ").append(method.toPythonReturnType()).append("\n");
        sb.append("        \"\"\"\n");
        
        // Build arguments JSON
        if (params.isEmpty()) {
            sb.append("        args = '[]'\n");
        } else {
            sb.append("        args = '['\n");
            for (int i = 0; i < params.size(); i++) {
                ParameterDefinition param = params.get(i);
                String paramName = param.toSnakeCaseName();
                String paramType = param.getType();
                
                if (i > 0) {
                    sb.append("        args += ','\n");
                }
                
                // Handle different types
                if (paramType.equals("String")) {
                    sb.append("        args += f'\"{").append(paramName).append("}\"'\n");
                } else if (paramType.equals("boolean") || paramType.equals("Boolean")) {
                    sb.append("        args += 'true' if ").append(paramName).append(" else 'false'\n");
                } else {
                    sb.append("        args += str(").append(paramName).append(")\n");
                }
            }
            sb.append("        args += ']'\n");
        }
        
        // Call peripheral
        sb.append("        result = peripheral.call(self.name, '").append(luaName).append("', args)\n");
        
        // Parse result based on return type
        String returnType = method.getReturnType();
        if (returnType == null || returnType.equals("void")) {
            sb.append("        return None\n");
        } else if (returnType.contains("[]") || returnType.contains("List")) {
            sb.append("        return _parse_string_array(result)\n");
        } else {
            sb.append("        return _parse_json_result(result)\n");
        }
        
        sb.append("\n");
    }
    
    /**
     * Generates a single Python file containing all peripherals.
     */
    public String generateSingleFile(PeripheralDefinitions definitions) {
        StringBuilder sb = new StringBuilder();
        
        sb.append("\"\"\"Auto-generated CC:Tweaked peripheral wrappers.\n\n");
        sb.append("This file contains wrapper classes for all discovered CC:Tweaked peripherals.\n");
        sb.append("Generated by PythonStubGenerator - do not edit manually.\n");
        sb.append("\"\"\"\n\n");
        sb.append("import peripheral\n\n");
        
        // Helper functions (same as above)
        sb.append("def _parse_json_result(json_str):\n");
        sb.append("    if json_str is None: return None\n");
        sb.append("    json_str = json_str.strip()\n");
        sb.append("    if json_str == 'null': return None\n");
        sb.append("    if json_str == 'true': return True\n");
        sb.append("    if json_str == 'false': return False\n");
        sb.append("    if json_str.startswith('\"') and json_str.endswith('\"'): return json_str[1:-1]\n");
        sb.append("    try:\n");
        sb.append("        return float(json_str) if '.' in json_str else int(json_str)\n");
        sb.append("    except: return json_str\n\n");
        
        sb.append("def _parse_string_array(json_str):\n");
        sb.append("    if not json_str or not json_str.strip().startswith('['): return []\n");
        sb.append("    inner = json_str.strip()[1:-1].strip()\n");
        sb.append("    if not inner: return []\n");
        sb.append("    return [i.strip().strip('\"') for i in inner.split(',') if i.strip()]\n\n");
        
        for (PeripheralDefinition peripheral : definitions.getPeripherals()) {
            generateClassInline(sb, peripheral);
        }
        
        return sb.toString();
    }
    
    private void generateClassInline(StringBuilder sb, PeripheralDefinition peripheral) {
        String className = peripheral.toPythonClassName();
        String peripheralType = peripheral.getType();
        
        sb.append("class ").append(className).append(":\n");
        sb.append("    \"\"\"Wrapper for ").append(peripheralType).append(" peripheral.\"\"\"\n\n");
        
        sb.append("    def __init__(self, name):\n");
        sb.append("        self.name = name\n");
        sb.append("        if not peripheral.is_present(name):\n");
        sb.append("            raise ValueError(f'Peripheral not found: {name}')\n\n");
        
        sb.append("    @staticmethod\n");
        sb.append("    def find():\n");
        sb.append("        name = peripheral.find('").append(peripheralType).append("')\n");
        sb.append("        return ").append(className).append("(name) if name else None\n\n");
        
        for (MethodDefinition method : peripheral.getMethods()) {
            generateMethod(sb, method);
        }
        
        sb.append("\n");
    }
    
    /**
     * Main entry point for running as a standalone tool.
     */
    public static void main(String[] args) throws IOException {
        if (args.length < 2) {
            System.err.println("Usage: PythonStubGenerator <definitions.json> <output-dir>");
            System.exit(1);
        }
        
        Path definitionsPath = Path.of(args[0]);
        Path outputDir = Path.of(args[1]);
        
        PeripheralDefinitions definitions = PeripheralDefinitions.loadFromFile(definitionsPath);
        
        PythonStubGenerator generator = new PythonStubGenerator();
        generator.generate(definitions, outputDir);
        
        System.out.println("Generated Python stubs for " + definitions.getPeripherals().size() + 
                         " peripherals in " + outputDir);
    }
}
